#!/bin/bash

# Beat vimgolf.com challenges
# code by Tom Allen (tom@nonserviam.net)
# now on twitter @TheRealTomAllen :)
# usage: winvimgolf <challenge id>


VIMGOLF=/var/lib/gems/1.8/bin/vimgolf
STRING="CHEATER" # edit this string to nothing shorter than 5 chars
CID=$@
VIMGOLFDIR=~/.vimgolf/put/

rm ${VIMGOLFDIR}/${CID}*
(
sleep 3 ;
OUTFILE=`find ${VIMGOLFDIR} -type f -iname \*${CID}\* | egrep -v '(.log|.output)$'` ;
cp ${VIMGOLFDIR}/$CID.output ${OUTFILE}
mv ${VIMGOLFDIR}/${CID}.log ${VIMGOLFDIR}/${CID}.log.old
echo ${STRING} > ${VIMGOLFDIR}/${CID}.log
) &
${VIMGOLF} put ${CID}
rm ${VIMGOLFDIR}/${CID}*
